spring:
  cloud:
    consul:
      discovery:
        instance-id: ai_assistant
        serviceName: myprefix-${spring.application.name}
        heartbeat:
          enabled: true
          ttl-value:  10
      host: localhost
      port: 8500
  application:
    name: ai_assistant
management:
  server:
    port: 4452